Added Traditional Chinese (zh_tw.json)
IMB11/SkinShuffle pull request #79
Opened 2024-07-03 10:49 UTC by yichifauzi

Do not merge yet! Please wait for @notlin4's review before merging.

2024-07-03 10:49 UTC, IMB11 commented
:+1:

2024-07-05 10:48 UTC, notlin4 requested changes

2024-07-05 10:48 UTC, notlin4 commented on src/main/resources/assets/skinshuffle/lang/zh_tw.json
> +  "skinshuffle.edit.source.file": "文件",
```suggestion
  "skinshuffle.edit.source.file": "檔案",
```

2024-07-05 10:48 UTC, notlin4 commented on src/main/resources/assets/skinshuffle/lang/zh_tw.json
> +  "skinshuffle.edit.source.invalid_url": "§4§n無效的 URL§r\n\nURL 無效。必須為有效的 §lhttp§r 或 §lhttps§r 協議 URL。",
```suggestion
  "skinshuffle.edit.source.invalid_url": "§4§n無效的網址§r\n\n網址無效。必須為有效的  §lhttp§r 或 §lhttps§r 協定網址。",
```

2024-07-05 10:48 UTC, notlin4 commented on src/main/resources/assets/skinshuffle/lang/zh_tw.json
> +  "skinshuffle.edit.source.unchanged": "保持現狀",
```suggestion
  "skinshuffle.edit.source.unchanged": "維持目前設定",
```

2024-07-05 10:48 UTC, notlin4 commented on src/main/resources/assets/skinshuffle/lang/zh_tw.json
> +  "skinshuffle.edit.customize.title": "預設設置",
```suggestion
  "skinshuffle.edit.customize.title": "預設設定",
```

2024-07-05 10:48 UTC, notlin4 commented on src/main/resources/assets/skinshuffle/lang/zh_tw.json
> +  "skinshuffle.carousel.confirmations.delete_preset.message": "您確定要刪除這個預設嗎？\n它將會永久消失！（真的很久！）",
```suggestion
  "skinshuffle.carousel.confirmations.delete_preset.message": "您確定要刪除這個預設嗎？\n它將會永遠消失！（非常久！）",
```

2024-07-07 17:13 UTC, IMB11 commented
Please mark this ready for review when you're ready :+1:

2024-07-07 17:41 UTC, notlin4 commented
I think this is ready to be merged.

2024-07-09 05:56 UTC, yichifauzi commented
Yeah, it's ready to merged

2024-07-09 13:09 UTC, merged